name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make fsanitize
      run: CXX=clang++ make asan
    - name: test with fsanitize
      run: |
        set -x
        ./ircserv 6667 123 &
        sleep 1
        echo "TEST test/Input/registration"
        cat test/Input/registration | netcat localhost 6667 -C -N
    - name: make debug
      run: CXX=clang++ make re debug
    - name: test leak
      run: |
        set -x
        valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./ircserv 6667 123 &
        sleep 1
        echo "TEST test/Input/registration"
        cat test/Input/registration | netcat localhost 6667 -C -N


